//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdate
    {
        public int ID { get; set; }
        public string namee { get; set; }
        public string email { get; set; }
        public string departmint { get; set; }
    }
}
